ContestSite/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, include, url
from django.contrib import admin

from tastypie.api import Api
from .api import *
from team.views import ScoreboardView

admin.autodiscover()

v1_api = Api(api_name="v1")
v1_api.register(UngradedResultResource())
v1_api.register(ExecutionResultResource())
v1_api.register(ProblemResource())
v1_api.register(ProblemResultResource())

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ContestSite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', ScoreboardView.as_view(), name='index'),

    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^team/', include('team.urls')),
    url(r'^judge/', include('judge.urls')),
    url(r'^api/', include(v1_api.urls)),
)

judge/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, url


from . import views

urlpatterns = patterns('',
	url(r'^grade/?$\/?', views.GradingView.as_view() , name="grading"),
	url(r'^user\/?$', views.UserListView.as_view(), name="user list"),
	url(r'^user/(\w+)/(\d+)\/?', views.UserDetailView.as_view(),
		name="user detail"),
	url(r'^result/(\d+)\/?', 
		views.ProblemResultDetailView.as_view(), name="problem result detail"),



)

team/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from . import views

urlpatterns = patterns('',
    url(r'^$', login_required( views.ScoreboardView.as_view() ), name='scoreboard'),

    url(r'^settings\/?', login_required( views.UserSettingsView.as_view() ), name="user settings"),

    url(r'problem/$', login_required( views.ProblemListView.as_view() ), name="problem list"),
    url(r'problem/(\d+)$', login_required( views.ProblemDetailView.as_view() ), name="problem detail"),
    url(r'problem/(\d+)/submit/(\d+)$', login_required( views.ProblemExecutionView.as_view() ), name="problem execution"),
    url(r'problem/(\d+)/file$', login_required( views.TextFileGeneratorView.as_view() ), name="text file generator"),

)

grading/models.py
from __future__ import absolute_import
import os
from datetime import timedelta,datetime
import logging
import sys

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.query import EmptyQuerySet

from pytz import timezone
from celery.contrib import rdb


# Create your models here.

def fixedTZData(dbDate):
	fixedDate = dbDate.astimezone(timezone(settings.TIME_ZONE))
	return fixedDate

class Compiler(models.Model):
	name 				= models.CharField(max_length=30)
	extension			= models.CharField(max_length=10, unique=True)
	compiled 			= models.BooleanField()
	compileCmd 			= models.TextField(blank=True)
	runCmd 				= models.TextField()

	def _getCmd(self, commandStr, solutionFile):
		fullname = solutionFile.path # Testing Phase
		directory = os.path.dirname(fullname)
		filename = os.path.basename(fullname)
		basename = os.path.splitext(filename)[0]
		command = commandStr.split(' ')
		def replace(c):
			c = c.replace('{{fullname}}', fullname) 	# /Users/test/programming/test.py
			c = c.replace('{{filename}}', filename)		# test.py
			c = c.replace('{{directory}}', directory)	# /Users/test/programming
			c = c.replace('{{basename}}', basename)		# test
			return c


		return	map(replace, command)

	def getCompileCmd(self, solutionFile):
		return self._getCmd(self.compileCmd, solutionFile)
	def getRunCmd(self, solutionFile):
		return self._getCmd(self.runCmd, solutionFile)

	def __unicode__(self):
		return self.name

class ProblemScore(models.Model):
	user 			= models.ForeignKey(User)
	problem 		= models.ForeignKey('problems.Problem')
	score 			= models.IntegerField()

class ProblemResult(models.Model):
	class Meta:
		ordering = ['-submissionTime']

	submissionTime 		= models.DateTimeField()
	graded				= models.BooleanField(default=settings.AUTO_GRADE)
	successful			= models.BooleanField(default=False)
	user 				= models.ForeignKey(User)
	problem 			= models.ForeignKey('problems.Problem')
	
	def failed(self):
		return self.problem.failed(self.user)

	def minsAgo(self):
		now = datetime.now(tz=timezone(settings.TIME_ZONE))
		delta = now - self.submissionTime
		minsAgo = delta.total_seconds() /60
		return int(minsAgo)

	def prettyTime(self):
		d = fixedTZData(self.submissionTime)
		now = datetime.now(tz=timezone(settings.TIME_ZONE))
		delta = d - now

		sixHours = timedelta(hours=6)
		if delta < sixHours:
			#no date
			return d.strftime("%I:%M %p")
		else:
			return d.strftime("%I:%M %p")
			# print with date

	def __unicode__(self):
		return self.problem.name + " correct? " + unicode(self.successful) + " @ " + unicode(self.submissionTime)

class ProblemSolution(models.Model):
	def get_uploaded_path(instance, filename):
		return os.path.join(instance.owner.username, filename)

	owner 				= models.ForeignKey(User)
	solution 			= models.FileField(upload_to=get_uploaded_path)

	def getFullName(self):
		return self.solution.path
	def getFilePath(self):
		return os.path.dirname(self.solution.path)
	def getFileName(self):
		return os.path.basename(self.solution.path)
	def getBaseName(self):
		filename = self.getFileName()
		(base, extension) = filename.split(".")
		return base
	def getExtension(self):
		filename = self.getFileName()
		(base, ext) = filename.split(".")
		return ext

	def compiler(self):
		compiler = Compiler.objects.get(extension=self.getExtension())
		return compiler

class ExecutionResult(models.Model):
	class Meta:
		ordering = ['-startTime']
	startTime			= models.DateTimeField()
	endTime				= models.DateTimeField()
	stdout				= models.TextField()
	stdin				= models.TextField(blank=True)
	stderr				= models.TextField(blank=True)
	command				= models.CharField(max_length=200)
	filename 			= models.CharField(max_length=200, blank=True)
	diff 				= models.TextField(blank=True)
	exitCode			= models.IntegerField()
	problemResult 		= models.OneToOneField(ProblemResult, null=True, blank=True)

grading/views.py
from django.shortcuts import render

# Create your views here.

judge/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.http import HttpResponse
from django import forms
import django.contrib.auth.models as auth
import django.contrib.auth.hashers as hasher
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator

from random import randint

from django.conf import settings
from django import forms

from team.models import UserSettings
from control.models import ContestSettings
from grading.models import ProblemResult, ExecutionResult
from team.library import progressBar

# Create your views here.

class JudgeView(View):
	@method_decorator(user_passes_test(lambda u: u.is_staff, login_url="/admin"))
	def dispatch(self, *args, **kwargs):
		return super(JudgeView, self).dispatch(*args, **kwargs)

class GradingView(JudgeView):
	def get(self, request):
		return render(request, "judge/grading.html")


class UserListView(JudgeView):
	def get(self, request):
		users = auth.User.objects.filter(is_staff=False)
		return render(request, "judge/user_list.html", {
				'users' : users,
			})

class UserDetailView(JudgeView):
	def get(self, request, username, userId):
		user = auth.User.objects.get(pk=userId)
		settings = UserSettings.objects.get_or_create(user=user)[0]

		results = ProblemResult.objects.filter(user=user)
		correct = len(settings.getCorrect())
		failed = len(settings.getFailed())

		(correctPercent, failedPercent) = progressBar(user)
		total = results.count()
		return render(request, "judge/user_detail.html", {
			'selectedUser'		: user,
			'results'			: results,
			'correct'			: correct,
			'failed'			: failed,
			'correctPercent'	: correctPercent,
			'failedPercent'		: failedPercent,
			'numTotal'			: total
		})

class ActionForm(forms.Form):
	action = forms.CharField(max_length=10, widget=forms.HiddenInput)

class ProblemResultDetailView(JudgeView):
	def get(self, request, resultId):
		actionForm = ActionForm()
		try:
			pResult = ProblemResult.objects.get(pk=resultId)
		except ProblemResult.DoesNotExist:
			pass #TODO
		problem = pResult.problem
		eResult = ExecutionResult.objects.get(problemResult=pResult)

		return render(request, "judge/problemresult_detail.html", {
			'problem'		: problem,
			'execution'		: eResult,
			'result'		: pResult,
			'form'			: actionForm,
		})

	def post(self, request, resultId):
		action = request.POST['action']
		result = ProblemResult.objects.get(pk=resultId)
		user = result.user
		if action == "regrade":
			result.graded = False
			result.save()
		elif action == "delete":
			execution = ExecutionResult.objects.get(problemResult=result)
			execution.delete()
			result.delete()
		return redirect('user detail', user.username, user.id)

class ContestSettingsForm(forms.ModelForm):
	class Meta:
		model = ContestSettings
		fields = ['startTime', 'endTime', 'paused']

class CreateUsersForm(forms.Form):
	userCount = forms.IntegerField(widget=forms.TextInput(attrs={"size":"3"}))


class ControlView(JudgeView):
	def get(self, request):
		contestsettings = ContestSettings.objects.get(pk=1)
		settings = ContestSettingsForm(instance=contestsettings)
		#userControl = UserControlForm()
		userCreate = CreateUsersForm()

		return render(request, "judge/control.html", {
			"contestSettings" : settings,
			#"userControl"		: userControl,
			"userCreate"		: userCreate,

		})

	def post(self, request):
		# contestupdate, createusers, cleardata
		action = request.GET['action']
		if action == "contestupate":
			settingsForm = ContestSettingsForm(request.POST)
			if settingsForm.is_valid():
				settingsForm.save()
		elif action == "createusers":
			userForm = CreateUsersForm(request.POST)
			userCount = int(userForm.data['userCount'])
			teamGroup = auth.Group.objects.get(name="Team")
			newUsers = []
			for i in range(userCount):
				username = "team%i" % (i+1)
				password = self.choosePassword()
				user = auth.User(username=username, password=hasher.make_password(password))
				user.save()
				teamGroup.user_set.add(user)
				row = (username, password)
				newUsers.append(row)
			teamGroup.save()
			return render(request, "judge/newUsers.html", {
				"users" : newUsers,
			})
		elif action == "cleardata":
			# delete all problem results
			ProblemResult.objects.all().delete()
			# delete all execution results
			ExecutionResult.objects.all().delete()
			# delete all users in group "Team"
			teamGroup = auth.Group.objects.get(name="Team")
			for user in teamGroup.user_set.all():
				user.delete()
			teamGroup.user_set.clear()
			teamGroup.save()
		return redirect('contest control')

	def choosePassword(self):
		choices = ["addle", "addle", "addle", "adieu", "adios", "adits", 
			"adman", "admen", "admit", "admix", "adobe", "adobo",
			"adopt", "adore", "adorn", "adown", "adoze", "adult", 
			"adunc", "adust", "adyta", "adzed", "adzes", "aecia",
			"aedes", "aegis", "aeons", "aerie", "afars", "affix", 
			"afire", "afoot", "afore", "afoul", "afrit", "after",
			"again", "agama", "agape", "agars", "agate", "agave", 
			"agaze", "agene", "agent", "agers", "agger", "aggie",
			"aggro", "aghas", "agile", "aging", "agios", "agism", 
			"agist", "agita", "aglee", "aglet", "agley", "aglow",
			"agmas", "agone", "agons", "agony", "agora", "agree",
			 "agria", "agues", "ahead", "ahing", "ahold", "ahull",
			"aided", "aider", "aides", "ailed", "aimed", "aimer",
			 "aioli", "aired", "airer", "airns", "airth", "airts",
			"aisle", "aitch", "aiver", "ajiva", "ajuga", "akees", 
			"akela", "akene", "alack", "alamo", "aland", "alane",]
		choice = choices[randint(0, len(choices)-1)]
		return choice

judge/templates/judge/grading.html
{% extends 'program/base.html' %}

{% block head %}
  <script src="/static/judge/js/grade.js" type="text/javascript"></script>
{% endblock %}

{%block body%}
 
<div class="row content" ng-app="Grading">
  <div class="col-md-12" ng-controller="Main as main">
    <div class="row">
      <div class="col-md-4">
        <div class="row">
          <p>
            <button ng-click="main.load()" class="btn btn-default btn-md glyphicon glyphicon-refresh"></button> 
          </p>
        </div>
        <div class="row">
          <table class="table table-hover border-dark ng-hide-[[loading]]">
            <thead>
              <tr class="border-dark">
                <th>Team&nbsp;<span class="caret"></span></th>

                {% comment %}
                <th><span class="glyphicon glyphicon-ok"></span>/<span class="glyphicon glyphicon-question-sign"></span>&nbsp;<span class="caret caret-reversed"></span></th>
                {% endcomment %}

                <th>Time</th>
                <th>Problem</th>
              </tr>
            </thead>
            <tbody>
              <!-- FOR________________________________________________ -->
              <tr ng-repeat="solution in solutions"
                ng-class="{tableSelected: solution == selected }"
                ng-click="main.setSelected(solution)"
                class="table-selected">
                <td>[[solution.team]]</td>
                <td>[[solution.minsAgo]] mins</td>
                <td>[[solution.problem.name]]</td>
              </tr>
              <!-- END FOR______________________________________________ -->
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-md-8 ng-hide-[[!selected]]" ng-model="main.selected">
        <div class="row">
          <div class="col-md-6">
            <h2>
              {% comment %}TODO(cleanup this comment)
              <span class="glyphicon glyphicon-ok" 
                  ng-if="selected.successful"></span>
              <span class="glyphicon glyphicon-question-sign" 
                  ng-if="!selected.successful"></span>
              {% endcomment %}
              [[selected.problem.name]]
            </h2>
            <h4>[[selected.team]]</h4>
          </div>
          <div class="col-md-6 text-right"><h2>[[selected.time]]</h2><h4>([[selected.minsAgo]] mins ago)</h4></div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <span class="btn-group">
              <button ng-click="main.gradeResult(true, selected)"
                  class="btn btn-default btn-md border-dark glyphicon glyphicon-ok"></button>
              <button ng-click="main.gradeResult(false, selected)"
                  class="btn btn-default btn-md border-dark glyphicon glyphicon-remove"></button>
            </span>
            <hr/>

            <h3>
              Grading Suggestion: 
              <span class="glyphicon glyphicon-ok" 
                style="color:green" 
                ng-if="selected.successful">
              </span>
              <span class="glyphicon glyphicon-remove"
                style="color:red"
                ng-if="!selected.successful">
              </span>
            </h3>
            
            <h3>Output</h3>

            <h4>stdout</h4>
            <div class="ace-hl ace-no-gutter" ng-bind-html="selected.execution.stdout"></div>

            <a ng-click="showExpected = !showExpected">
              <span ng-show="!showExpected">Show</span>
              <span ng-show="showExpected">Hide</span>
                expected output
            </a>
            <span ng-show="showExpected"> <!-- hiding the expected output by default. -->
              <h4>Expected Output</h4>
              <div class="ace-hl ace-no-gutter" ng-bind-html="selected.problem.outputSubmit"></div>
            </span>

            <h4>Diff</h4>
            <div class="ace-hl ace-no-gutter" ng-bind-html="selected.execution.diff"></div>

            <h3>Running Time</h3>
            <p>
              [[main.runningTime(selected.execution.startTime, selected.execution.endTime)]] ms
            </p>

            <h3>Command</h3>
            <div class="ace-hl ace-no-gutter" ng-bind-html="selected.execution.command"></div>

            <h3>stdin</h3>
            <div class="ace-hl ace-no-gutter" ng-bind-html="selected.execution.stdin"></div>

            <h3>stderr</h3>
            <div class="ace-hl ace-no-gutter" ng-bind-html="selected.execution.stderr"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{%endblock%}

judge/templates/judge/newUsers.html
<h1>New Users</h1>
<p>This is the only record of new users, please save!</p>
<p><a href="{% url 'contest control' %}">back to controls</a></p>
<table border="1">
<thead>
	<tr>
		<td>username</td>
		<td>password</td>
	</tr>
</thead>
<tbody>
	{% for username,password in users %}
		<tr><td>{{username}}</td><td>{{password}}</td></tr>
	{% endfor %}
</tbody>

</table>

judge/templates/judge/problemresult_detail.html
{% extends 'program/base.html' %}

{% block body %}

<div class="col-md-12">
			<div class="row">
				<div class="col-md-6">

					<h2>
						{% if result.successful and result.graded %}
						<span class="glyphicon glyphicon-ok"></span>
						{% elif not result.successful and result.graded %}
							<span class="glyphicon glyphicon-remove"></span>
						{% else %}
							<span class="glyphicon glyphicon-question-sign"></span>
						{% endif %}
						{{problem.name}}
					</h2>
					<h4>{{result.user.usersettings.teamName}} ({{result.user.username}})</h4>
				</div>
				<div class="col-md-6 text-right">
					<h2>{{result.prettyTime}}</h2><h4>({{result.minsAgo}} mins ago)</h4>
					<form action="#" method="POST" role="form">{% csrf_token %}
					{{ form.as_p }}
					<span class="btn-group">
						<button onclick="$('#id_action').val('regrade');"
								class="btn btn-default btn-md border-dark">Regrade</button>
						<button onclick="$('#id_action').val('delete');"
								class="btn btn-default btn-md border-dark">Delete</button>
					</span>
					</form>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					
					<hr/>
					<h3>Output Diff</h3>
					<pre class="hljs hljs-init"><code>{{execution.diff}}</code></pre>
					<h3>Running Time</h3>
					<p>{{execution.startTime}} seconds</p> <!-- TODO -->
					<h3>Command</h3>
					<pre class="hljs hljs-init"><code>{{execution.command}}</code></pre>
					<h3>Stdin</h3>
					<pre class="hljs hljs-init"><code>{{execution.stdin}}</code></pre>
					<h3>Stderr</h3>
					<pre class="hljs hljs-init"><code>{{execution.stderr}}</code></pre>
				</div>
			</div>
		</div>

{% endblock %}

judge/templates/judge/user_detail.html
{% extends 'program/base.html' %}

{% block body %}

<div class="row container">

<div class="row">
<div class="col-md-8">
	<h1>{{selectedUser.usersettings.teamName}}</h1>
</div>
<div class="col-md-4">
	<h2 class="pull-right">{{selectedUser.username}}</h2>
</div>
</div>

<div class="row">
<div class="col-md-9">
	<h2>Submissions</h2>
	<table class="table table-hover border-dark">
		<thead> <tr class="border-dark">
			<td>Problem</td>
			<td>Solved</td>
			<td>Graded</td>
			<td>Time&nbsp;<span class="caret caret-reversed"></td>
		</tr> </thead>

		<tbody>
		{% for result in results %}
			<tr>
				<td><a href="{% url 'problem result detail' result.id %}">{{result.problem.name}}</a></td>
				<td>
					{% if result.successful %}
					<span class="glyphicon glyphicon-ok"></span>
					{% else %}
					<span class="glyphicon glyphicon-remove"></span>
					{% endif %}
				</td>
				<td>
					{% if result.graded %}
					<span class="glyphicon glyphicon-ok"></span>
					{% else %}
					<span class="glyphicon glyphicon-remove"></span>
					{% endif %}
				</td>
				<td>{{result.minsAgo}} mins ago</td>
		{% endfor %}
		</tbody>
	</table>
</div>

<div class="col-md-3">
    <h2>Stats</h2>
	<div class="progress">
		<div class="progress-bar progress-bar-success" style="width: {{correctPercent}}%"></div>
		<div class="progress-bar progress-bar-danger" style="width: {{failedPercent}}%"></div>
    </div>
	<h4><span class="glyphicon glyphicon-ok"></span> {{correct}} &nbsp;&nbsp;
		<span class="glyphicon glyphicon-remove"></span> {{failed}}</h4>
	<h4>Total - {{numTotal}}</h4>
</div>
</div>

<div class="row">
<div class="col-md-12">
	<h1>About</h1>
</div>
</div>

</div>

{% endblock %}

judge/templates/judge/user_list.html
{% extends 'program/base.html' %}

{% block body %}
<div class="row content">
<div class="col-md-12">
<div class="col-md-8">
	<h1>Teams</h1>

	<table class="table table-hover">
		<thead>
		<tr>
			<th>Username</th>
			<th>Team Name</th>
			<th>Score</th>
		</tr>
		<thead>

		<tbody>
		{% for u in users %}
		 <tr>
 			{% url 'user detail' u.username u.id as user_detail %}
		 	<td><a href="{{user_detail}}">{{u.username}}</a></td>
		 	<td><a href="{{user_detail}}">{{u.usersettings.teamName}}</a></td>
		 	<td>{{u.usersettings.score}}</td>
	 	</tr>
		 {% endfor %}
		 </tbody>

	</table>

</div>
</div>
</div>
{% endblock %}